import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import QueryProvider from "./QueryProvider";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} ${figtree.className} antialiased`}>
        <QueryProvider>

          {children}
          <ToastContainer />
        </QueryProvider>

      </body>
    </html>
  );
}